### ISSUE TITLE
瀑布流实现

### ISSUE THREAD

**Issue by jiatingyu** [jiatingyu/trainee#1]
# css3 的 column 属性
 ```css 
<style>
    .wrap{
      column-count: 3; // 每列展示多少
      column-gap : 10px; // 每列的之间的间距
    }
    .item{
      border: 1px solid #ccc;
      margin-bottom: 5px;
    }
    .item  img{
        width: 100%;
        height: 100%;
      }
  </style>
```
# flex 实现
```css 
<style>
  .wrap{
    display:flex;
    flex-flow:column wrap; // 使用cloumn
    height: 100vh; // 高度必须要设置
  }
  .item {
    width: calc(100%/3 - 20px)
  }
  .item img{
    width: 100%;
  }
</style>
```
# 绝对定位

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    /* v1 */
    /* .wrap{
      column-count: 3;
      column-gap : 10px;
    }
    .item{
      border: 1px solid #ccc;
      margin-bottom: 5px;

    }
    .item  img{
        width: 100%;
        height: 100%;
      } */
      /* v2 */
      /* .wrap{
        display:flex;
        flex-flow:column wrap;
        height: 100vh;
      }
      .item {
        width: calc(100%/3 - 20px)
      }
      .item img{
        width: 100%;
      } */

      body{
        background-color: #cccccc;
      }
  </style>
</head>
  瀑布流的实现
  <!-- <div class="wrap">
    <div class="item">
      <img src="./1.jpg"/>
    </div>
    <div class="item">
      <img src="./2.jpg"/>
    </div>
    <div class="item">
      <img src="./3.jpg"/>
    </div>
    <div class="item">
      <img src="./4.jpg"/>
    </div>
    <div class="item">
      <img src="./1.jpg"/>
    </div>
    <div class="item">
      <img src="./2.jpg"/>
    </div>
    <div class="item">
      <img src="./3.jpg"/>
    </div>
    <div class="item">
      <img src="./4.jpg"/>
    </div>
  </div> -->
  <div id="render"></div>
  <div  id='hidearea' style="display:none">隐藏区域</div>
  <script>
    // 实现 
    let imgInfoList = []
    localImgList=[
      './1.jpeg',
      './2.jpeg',
      './3.jpeg',
      './4.jpeg',
      './5.jpeg',
      './6.jpeg',
      './8.jpeg',
      './9.jpeg',
      './10.jpeg',
      './11.jpeg',
      './12.jpeg',
      './13.jpeg',
    ]
    let loadArr = []
    function initImagePosition(){
      let columnNum = 5;
      let imgWidth =parseInt( document.body.clientWidth / 5 )
      let indexArr = []
      let columnHeightArr = []
      localImgList.forEach((ele,index) => {
        let idx = index%columnNum
        let url = localImgList[index]
        let img = new Image()
        img.src = url
        let hidearea = document.getElementById('hidearea')
        img.onload = () =>{
          let height = img.height
          setPosition(idx,index,img,height)
          loadArr.push(idx)
          showImgInfo()
        }
        hidearea.appendChild(img)
      });
      let gi = 0
      function setPosition(i,index,img,height){
        if(gi < columnNum){
          // 第一行
          img.style.position = "absolute"
          img.style.top = "0px"
          img.style.left = gi*imgWidth+"px"
          img.style.width = (imgWidth-10)+"px"
          img.style.height = height-10+"px"
          imgInfoList[gi] = img
          columnHeightArr[gi] = height
        }else{ 
          // 第二行以后的
          let minHeight = Math.min.apply(null,columnHeightArr)
          let mingHeightIndex = columnHeightArr.indexOf(minHeight)
          img.style.position = "absolute"
          img.style.top = minHeight+"px"
          img.style.left = mingHeightIndex*imgWidth+"px"
          img.style.width = (imgWidth-10)+"px"
          img.style.height = height-10+"px"
          columnHeightArr.splice(mingHeightIndex,1,minHeight+height)
          imgInfoList[gi] = img
          console.log(columnHeightArr)
       
        }
        gi++
      }
    }
    
    function showImgInfo() {
      if(loadArr.length === localImgList.length){
        console.log(imgInfoList)
        // 把数据渲染出来
        let renderTree = document.getElementById('render')
        imgInfoList.forEach(imgInfo => {
          renderTree.appendChild(imgInfo)
        })
      }
    }
    initImagePosition()

    console.log(imgInfoList)
  </script>
<body>
</body>

</html>
```
